language: ruby
rvm:
  - 2.1.2
before_script:
  - "gem install rubocop"
  - "npm install -g jshint"
  - "npm install -g csslint"
  - "npm install -g csscomb"
  - "npm install -g htmllint"
script: "./.linter/run_tests.rb"
notifications:
  hipchat:
    rooms:
      - 94f92ca23f75a2b38fa38ed847a221@Tinkerers
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    notify: true
