language: ruby
rvm:
  - 2.0.0
before_script:
  - "gem install rubocop"
  - "npm install -g jshint"
  - "npm install -g csslint"
  - "npm install -g csscomb"
  - "npm install -g htmllint"
script: "./.linter/run_tests.rb"
notifications:
  hipchat:
    rooms:
      - secure: "elW4Lz1aT0A5QUp/5LE2vqqnyvuPw+q59+nOUuvwmjC4KG8PURvwahWsaMTr3XfKaIR9pKPRrtUCcEAnFVB7tpjYEC8G0ZdUQqRcuFSbeJP9LqA/2jkioM8rbZXn8SL49CgB1TRRKRW3NZ0rJgkh+8+QfGAnnP30n4zIkEVMbZo="
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
